"""Update Image model

Revision ID: 5c6d58d808f2
Revises: 5c0c0f9a65eb
Create Date: 2026-01-08 20:04:45.673793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6d58d808f2'
down_revision: Union[str, Sequence[str], None] = '5c0c0f9a65eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('images', sa.Column('checksum', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_images_checksum'), 'images', ['checksum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_checksum'), table_name='images')
    op.drop_column('images', 'checksum')
    op.drop_column('images', 'file_name')
    # ### end Alembic commands ###
